---
config:
  theme: neo-dark
  look: neo
  layout: elk
---
flowchart TB
 subgraph CLIENT["Client dApp"]
        Browser["Browser"]
        Nodejs["Node.js"]
  end
 subgraph LIBRARY["Starknet JS"]
        Interface["Instance"]
        Account["Account"]
        Contract["Contract"]
        Provider["Provider"]
        Channel["Channel"]
        Transport["Transport"]
        Utils["Utils"]
        Signer["Signer"]
  end
 subgraph NETWORK["Starknet Network"]
        Starknet["Starknet RPC Node"]
  end
    Browser e1@--> Interface
    Nodejs e2@--> Interface
    Interface --> Provider & Account & Contract & Channel
    Contract e3@--> Account
    Contract --> Provider
    Account e4@--> Provider
    Provider e5@--> Channel
    Channel e6@--> Transport
    Transport e7@-- "http(s):// · ws(s)://" --> Starknet
    Interface@{ shape: dbl-circ}
    e1@{ animation: slow }
    e3@{ animation: slow }
    e4@{ animation: slow }
    e5@{ animation: slow }
    e6@{ animation: slow }
    e7@{ animation: fast }
