name: _ Run Release
on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        default: false
      dry-run:
        type: boolean
        default: false
    secrets:
      # populated automatically
      # GITHUB_TOKEN:
      #   required: true
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci --ignore-scripts ${{ inputs.dry-run }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --debug ${{ inputs.debug }} --dry-run ${{ inputs.dry-run }}
