name: '[Manual] Test Devnet'
on:
  workflow_dispatch:
    inputs:
      ignore-scripts:
        description: 'Ignore scripts'
        type: boolean
        default: false

jobs:
  tests:
    name: Run test on rpc-devnet

    uses: ./.github/workflows/_test.yml
    with:
      use-devnet: true
      ignore-scripts: ${{ inputs.ignore-scripts }}
