name: '[Manual] Test Testnet'
on:
  workflow_dispatch:
    inputs:
      ignore-scripts:
        description: 'Ignore scripts'
        type: boolean
        default: false
      fail-fast:
        description: 'Fail fast'
        type: boolean
        default: false

      matrix-node-juno:
        description: 'Node: Juno'
        type: boolean
        default: true
      matrix-node-pathfinder:
        description: 'Node: Pathfinder'
        type: boolean
        default: true
      matrix-protocol-rpc:
        description: 'Protocol: RPC'
        type: boolean
        default: true
      matrix-protocol-ws:
        description: 'Protocol: WS'
        type: boolean
        default: true
      matrix-version-v0_7:
        description: 'RPC version: 0.7'
        type: boolean
        default: true
      matrix-version-v0_8:
        description: 'RPC version: 0.8'
        type: boolean
        default: true

jobs:
  tests:
    name: Run test on ${{ matrix.node }} ${{ matrix.protocol }} ${{ matrix.version }}
    strategy:
      max-parallel: 1
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        protocol: [RPC, WS]
        node: [Juno, Pathfinder]
        version: [v0_7, v0_8]
        exclude:
          - version: v0_7
            protocol: WS

    uses: ./.github/workflows/_test.yml
    with:
      ignore-scripts: ${{ inputs.ignore-scripts }}
      protocol: ${{ matrix.protocol }}
      node: ${{ matrix.node }}
      version: ${{ matrix.version }}
    secrets: inherit
